Repository weady-umc/weady-server, pull requests merged in 2025-08, with the labels that each got.

#109 [FEAT] 웨디카이브 큐레이션 응답 수정/ 지역에 따른 큐레이션 제공 API 구현
  src/main/java/com/weady/weady/common/error/errorCode/LocationErrorCode.java
  src/main/java/com/weady/weady/domain/curation/dto/Response/CurationByLocationResponseDto.java
  src/main/java/com/weady/weady/domain/curation/entity/Curation.java
  src/main/java/com/weady/weady/domain/curation/mapper/CurationCategoryMapper.java
  src/main/java/com/weady/weady/domain/curation/repository/curationCategory/CurationCategoryRepository.java
  src/main/java/com/weady/weady/domain/curation/service/CurationService.java
  src/main/java/com/weady/weady/domain/location/repository/LocationRepository.java
  src/main/java/com/weady/weady/domain/weadychive/controller/curation/WeadychiveController.java
  src/main/java/com/weady/weady/domain/weadychive/dto/curation/Response/CurationDto.java
  src/main/java/com/weady/weady/domain/weadychive/mapper/curation/WeadychiveCurationMapper.java
  src/main/java/com/weady/weady/domain/weadychive/service/curation/WeadychiveCurationService.java
  src/main/java/com/weady/weady/domain/weather/repository/DailySummaryRepository.java
Labels: ✨ feat

#110 [FEAT] Board / 옷 정보 태그 기능 추가 및 현재 위치 기준 날씨 정보 저장 API 구현
  src/main/java/com/weady/weady/domain/board/dto/request/BoardBrandRequestDto.java
  src/main/java/com/weady/weady/domain/board/dto/request/BoardCreateRequestDto.java
  src/main/java/com/weady/weady/domain/board/dto/response/BoardBrandResponseDto.java
  src/main/java/com/weady/weady/domain/board/dto/response/BoardImgResponseDto.java
  src/main/java/com/weady/weady/domain/board/dto/response/BoardResponseDto.java
  src/main/java/com/weady/weady/domain/board/entity/board/Board.java
  src/main/java/com/weady/weady/domain/board/entity/board/BoardBrand.java
  src/main/java/com/weady/weady/domain/board/entity/board/ReportType.java
  src/main/java/com/weady/weady/domain/board/mapper/BoardMapper.java
  src/main/java/com/weady/weady/domain/board/service/BoardService.java
  src/main/java/com/weady/weady/domain/weather/controller/WeatherController.java
  src/main/java/com/weady/weady/domain/weather/dto/response/LocationTagResponseDto.java
  src/main/java/com/weady/weady/domain/weather/mapper/WeatherMapper.java
  src/main/java/com/weady/weady/domain/weather/service/WeatherService.java
Labels: ✨ feat

#127 [RELEASE] dev > release 배포
  src/main/java/com/weady/weady/domain/board/dto/request/BoardCreateRequestDto.java
  src/main/java/com/weady/weady/domain/board/dto/response/BoardHomeResponseDto.java
  src/main/java/com/weady/weady/domain/board/entity/board/Board.java
  src/main/java/com/weady/weady/domain/board/repository/BoardRepository.java
  src/main/java/com/weady/weady/domain/board/service/BoardService.java
  src/main/java/com/weady/weady/domain/scheduler/SnapshotScheduler.java
  src/main/java/com/weady/weady/domain/weather/service/WeatherService.java
Labels: 🛠️ build

#138 [FIX] Fashion / 옷차림 요약 정보 조회 시 500 에러 해결
  src/main/java/com/weady/weady/domain/fashion/service/FashionService.java
  src/main/java/com/weady/weady/domain/user/repository/UserFavoriteLocationRepository.java
Labels: 🐛 fix

#141 [FIX] Weatther / 중기예보 에러 수정
  src/main/java/com/weady/weady/domain/weather/mapper/WeatherMapper.java
Labels: 🐛 fix

#142 [RELEASE] dev > release 배포
  src/main/java/com/weady/weady/domain/fashion/service/FashionService.java
  src/main/java/com/weady/weady/domain/user/entity/User.java
  src/main/java/com/weady/weady/domain/user/repository/UserFavoriteLocationRepository.java
  src/main/java/com/weady/weady/domain/user/service/UserService.java
  src/main/java/com/weady/weady/domain/weather/mapper/WeatherMapper.java
Labels: 🛠️ build

#145 [RELEASE] dev > release 배포
  src/main/java/com/weady/weady/domain/fashion/service/FashionService.java
  src/main/java/com/weady/weady/domain/user/repository/UserFavoriteLocationRepository.java
Labels: 🛠️ build

#148 [REFACTOR] Board / 보드 및 댓글 전체 조회 로직 변경
  src/main/java/com/weady/weady/domain/board/controller/BoardController.java
  src/main/java/com/weady/weady/domain/board/entity/board/Board.java
  src/main/java/com/weady/weady/domain/board/repository/BoardRepository.java
  src/main/java/com/weady/weady/domain/board/repository/CommentRepository.java
  src/main/java/com/weady/weady/domain/board/service/BoardService.java
  src/main/java/com/weady/weady/domain/board/service/CommentService.java
  src/main/java/com/weady/weady/domain/weadychive/dto/board/response/ScrapBoardResponseDto.java
  src/main/java/com/weady/weady/domain/weadychive/mapper/board/WeadychiveBoardMapper.java
Labels: ♻️ refactor

#162 [RELEASE] dev > release
  src/main/java/com/weady/weady/domain/user/dto/response/GetMyPageResponse.java
  src/main/java/com/weady/weady/domain/user/mapper/MyPageMapper.java
  src/main/java/com/weady/weady/domain/user/service/MyPageService.java
Labels: 🛠️ build

#168 release > main V1 완성
  src/main/java/com/weady/weady/common/error/errorCode/BoardErrorCode.java
  src/main/java/com/weady/weady/domain/board/controller/BoardController.java
  src/main/java/com/weady/weady/domain/board/entity/board/Board.java
  src/main/java/com/weady/weady/domain/board/repository/BoardRepository.java
  src/main/java/com/weady/weady/domain/board/service/BoardService.java
  src/main/java/com/weady/weady/domain/curation/controller/CurationController.java
  src/main/java/com/weady/weady/domain/curation/dto/Request/CurationBannerImgRequestDto.java
  src/main/java/com/weady/weady/domain/curation/dto/Response/CurationDto.java
  src/main/java/com/weady/weady/domain/curation/entity/Curation.java
  src/main/java/com/weady/weady/domain/curation/mapper/CurationCategoryMapper.java
  src/main/java/com/weady/weady/domain/curation/service/CurationService.java
  src/main/java/com/weady/weady/domain/user/dto/response/GetMyPageResponse.java
  src/main/java/com/weady/weady/domain/user/mapper/MyPageMapper.java
  src/main/java/com/weady/weady/domain/user/service/MyPageService.java
  src/main/java/com/weady/weady/domain/weadychive/repository/board/WeadychiveBoardRepository.java
  src/main/java/com/weady/weady/domain/weather/scheduler/WeatherScheduler.java
Labels: 🛠️ build
