Repository weady-umc/weady-server, pull requests merged in 2025-07, with the labels that each got.

#5 [FEAT] Auth / 인증객체 가져오는 메소드 작성, 예시코드 작성
  src/main/java/com/weady/weady/domain/user/controller/ExampleUserController.java
  src/main/java/com/weady/weady/domain/user/dto/ExampleUserRequest.java
  src/main/java/com/weady/weady/domain/user/dto/ExampleUserResponse.java
  src/main/java/com/weady/weady/domain/user/mapper/UserMapper.java
  src/main/java/com/weady/weady/domain/user/repository/UserRepository.java
  src/main/java/com/weady/weady/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/weady/weady/domain/user/service/ExampleUserService.java
  src/main/java/com/weady/weady/global/common/error/errorCode/AuthErrorCode.java
  src/main/java/com/weady/weady/global/util/SecurityUtil.java
Labels: ✨ feat

#24 [FIX] Swagger / 스웨거 설정 오류 수정
  build.gradle
  src/main/java/com/weady/weady/domain/board/controller/BoardController.java
  src/main/java/com/weady/weady/global/config/SwaggerConfig.java
Labels: 🐛 fix

#37 [REFACTOR] Location / 지역 hCode 변수명 변경
  src/main/java/com/weady/weady/domain/location/entity/Location.java
  src/main/java/com/weady/weady/domain/location/repository/JpaLocationRepository.java
  src/main/java/com/weady/weady/domain/location/repository/LocationRepository.java
  src/main/java/com/weady/weady/domain/location/repository/LocationRepositoryImpl.java
  src/main/java/com/weady/weady/domain/user/service/UserFavoriteLocationService.java
Labels: ♻️ refactor

#44 [REFACTOR] Global / repository 구조 변경
  src/main/java/com/weady/weady/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/com/weady/weady/domain/auth/repository/RefreshTokenRepositoryImpl.java
  src/main/java/com/weady/weady/domain/board/repository/BoardRepository.java
  src/main/java/com/weady/weady/domain/board/repository/BoardRepositoryImpl.java
  src/main/java/com/weady/weady/domain/board/repository/JpaBoardRepository.java
  src/main/java/com/weady/weady/domain/curation/repository/curationCategory/CurationCategoryRepository.java
  src/main/java/com/weady/weady/domain/tags/repository/clothesStyleCategory/ClothesStyleCategoryRepository.java
  src/main/java/com/weady/weady/domain/tags/repository/clothesStyleCategory/JpaClothesStyleCategoryRepository.java
  src/main/java/com/weady/weady/domain/tags/repository/clothesStyleCategory/StyleCategoryRepositoryImpl.java
  src/main/java/com/weady/weady/domain/tags/repository/season/JpaSeasonRepository.java
  src/main/java/com/weady/weady/domain/tags/repository/season/SeasonRepository.java
  src/main/java/com/weady/weady/domain/tags/repository/season/SeasonRepositoryImpl.java
  src/main/java/com/weady/weady/domain/tags/repository/temperature/JpaTemperatureRepository.java
  src/main/java/com/weady/weady/domain/tags/repository/temperature/TemperatureRepository.java
  src/main/java/com/weady/weady/domain/tags/repository/temperature/TemperatureRepositoryImpl.java
  src/main/java/com/weady/weady/domain/tags/repository/weather/JpaWeatherRepository.java
  src/main/java/com/weady/weady/domain/tags/repository/weather/WeatherRepository.java
  src/main/java/com/weady/weady/domain/tags/repository/weather/WeatherRepositoryImpl.java
  src/main/java/com/weady/weady/domain/user/repository/JpaUserRepository.java
  src/main/java/com/weady/weady/domain/user/repository/UserRepository.java
  src/main/java/com/weady/weady/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/weady/weady/domain/weadychive/repository/curation/JpaWeadychiveCurationRepository.java
  src/main/java/com/weady/weady/domain/weadychive/repository/curation/WeadychiveCurationRepository.java
  src/main/java/com/weady/weady/domain/weadychive/repository/curation/WeadychiveCurationRepositoryImpl.java
  src/main/java/com/weady/weady/domain/weadychive/service/curation/WeadychiveCurationService.java
Labels: ♻️ refactor

#46 [BUILD] global / github action yml 파일 작성
  .github/workflows/ci-cd.yml
Labels: 🛠️ build

#52 [BULID] Dockerfile 작성
  .dockerignore
  Dockerfile
Labels: 🛠️ build

#51 [FEAT] User / 유저 즐겨찾기 지역 조회 api 구현
  src/main/java/com/weady/weady/WeadyApplication.java
  src/main/java/com/weady/weady/domain/location/entity/Location.java
  src/main/java/com/weady/weady/domain/location/repository/JpaLocationRepository.java
  src/main/java/com/weady/weady/domain/location/repository/LocationRepository.java
  src/main/java/com/weady/weady/domain/location/repository/LocationRepositoryImpl.java
  src/main/java/com/weady/weady/domain/user/controller/ExampleUserController.java
  src/main/java/com/weady/weady/domain/user/controller/UserController.java
  src/main/java/com/weady/weady/domain/user/controller/UserFavoriteLocationController.java
  src/main/java/com/weady/weady/domain/user/dto/ExampleUserRequest.java
  src/main/java/com/weady/weady/domain/user/dto/request/AddUserFavoriteLocationRequest.java
  src/main/java/com/weady/weady/domain/user/dto/request/ExampleUserRequest.java
  src/main/java/com/weady/weady/domain/user/dto/request/UserRequest.java
  src/main/java/com/weady/weady/domain/user/dto/response/AddUserFavoriteLocationResponse.java
  src/main/java/com/weady/weady/domain/user/dto/response/ExampleUserResponse.java
  src/main/java/com/weady/weady/domain/user/dto/response/GetUserFavoriteLocationResponse.java
  src/main/java/com/weady/weady/domain/user/dto/response/UserResponse.java
  src/main/java/com/weady/weady/domain/user/mapper/UserFavoriteLocationMapper.java
  src/main/java/com/weady/weady/domain/user/mapper/UserMapper.java
  src/main/java/com/weady/weady/domain/user/repository/UserFavoriteLocationRepository.java
  src/main/java/com/weady/weady/domain/user/service/ExampleUserService.java
  src/main/java/com/weady/weady/domain/user/service/UserFavoriteLocationService.java
  src/main/java/com/weady/weady/domain/user/service/UserService.java
  src/main/java/com/weady/weady/domain/weather/entity/DailySummary.java
Labels: ✨ feat

#54 [BUILD] 1차 배포
  src/main/java/com/weady/weady/WeadyApplication.java
  src/main/java/com/weady/weady/domain/board/repository/BoardRepository.java
  src/main/java/com/weady/weady/domain/fashion/controller/FashionController.java
  src/main/java/com/weady/weady/domain/fashion/dto/Response/FashionSummaryResponseDto.java
  src/main/java/com/weady/weady/domain/fashion/entity/Fashion.java
  src/main/java/com/weady/weady/domain/fashion/entity/FashionRule.java
  src/main/java/com/weady/weady/domain/fashion/repository/FashionRepository.java
  src/main/java/com/weady/weady/domain/fashion/service/FashionService.java
  src/main/java/com/weady/weady/domain/location/entity/Location.java
  src/main/java/com/weady/weady/domain/location/repository/JpaLocationRepository.java
  src/main/java/com/weady/weady/domain/location/repository/LocationRepository.java
  src/main/java/com/weady/weady/domain/location/repository/LocationRepositoryImpl.java
  src/main/java/com/weady/weady/domain/user/controller/ExampleUserController.java
  src/main/java/com/weady/weady/domain/user/controller/UserController.java
  src/main/java/com/weady/weady/domain/user/controller/UserFavoriteLocationController.java
  src/main/java/com/weady/weady/domain/user/dto/ExampleUserRequest.java
  src/main/java/com/weady/weady/domain/user/dto/request/AddUserFavoriteLocationRequest.java
  src/main/java/com/weady/weady/domain/user/dto/request/ExampleUserRequest.java
  src/main/java/com/weady/weady/domain/user/dto/request/UserRequest.java
  src/main/java/com/weady/weady/domain/user/dto/response/AddUserFavoriteLocationResponse.java
  src/main/java/com/weady/weady/domain/user/dto/response/ExampleUserResponse.java
  src/main/java/com/weady/weady/domain/user/dto/response/GetUserFavoriteLocationResponse.java
  src/main/java/com/weady/weady/domain/user/dto/response/UserResponse.java
  src/main/java/com/weady/weady/domain/user/mapper/UserFavoriteLocationMapper.java
  src/main/java/com/weady/weady/domain/user/mapper/UserMapper.java
  src/main/java/com/weady/weady/domain/user/repository/UserFavoriteLocationRepository.java
  src/main/java/com/weady/weady/domain/user/service/ExampleUserService.java
  src/main/java/com/weady/weady/domain/user/service/UserFavoriteLocationService.java
  src/main/java/com/weady/weady/domain/user/service/UserService.java
  src/main/java/com/weady/weady/domain/weather/entity/DailySummary.java
  src/main/java/com/weady/weady/domain/weather/entity/LocationWeatherSnapshot.java
  src/main/java/com/weady/weady/domain/weather/repository/LocationWeatherSnapshotRepository.java
  src/main/java/com/weady/weady/global/common/error/errorCode/FashionErrorCode.java
  src/main/java/com/weady/weady/global/common/error/errorCode/WeatherErrorCode.java
Labels: 🛠️ build

#62 [FEAT] 중기예보 Entity 작성, 단기예보 Entity 수정
  src/main/java/com/weady/weady/domain/user/controller/UserController.java
  src/main/java/com/weady/weady/domain/weather/entity/LocationWeatherShortDetail.java
  src/main/java/com/weady/weady/domain/weather/entity/SkyCode.java
  src/main/java/com/weady/weady/domain/weather/entity/WeatherMidDetail.java
Labels: ✨ feat, ♻️ refactor

#59 [FEAT] Board / 게시글 수정 및 삭제 API 구현
  src/main/java/com/weady/weady/domain/board/controller/BoardController.java
  src/main/java/com/weady/weady/domain/board/dto/response/BoardGoodResponseDto.java
  src/main/java/com/weady/weady/domain/board/dto/response/BoardResponseDto.java
  src/main/java/com/weady/weady/domain/board/entity/board/Board.java
  src/main/java/com/weady/weady/domain/board/mapper/BoardMapper.java
  src/main/java/com/weady/weady/domain/board/repository/BoardRepository.java
  src/main/java/com/weady/weady/domain/board/service/BoardService.java
  src/main/java/com/weady/weady/global/common/error/errorCode/BoardErrorCode.java
Labels: ✨ feat

#68 [FEAT] User / 유저 기본 위치 업데이트 api 구현
  src/main/java/com/weady/weady/domain/user/controller/UserFavoriteLocationController.java
  src/main/java/com/weady/weady/domain/user/dto/request/setDefaultLocationRequest.java
  src/main/java/com/weady/weady/domain/user/service/UserFavoriteLocationService.java
Labels: ✨ feat

#67 [FEAT] Board / 게시물 저장 및 숨김 API 구현
  src/main/java/com/weady/weady/common/error/errorCode/BoardErrorCode.java
  src/main/java/com/weady/weady/domain/board/controller/BoardController.java
  src/main/java/com/weady/weady/domain/board/entity/board/Board.java
  src/main/java/com/weady/weady/domain/board/entity/board/BoardHidden.java
  src/main/java/com/weady/weady/domain/board/mapper/BoardMapper.java
  src/main/java/com/weady/weady/domain/board/repository/BoardHiddenRepository.java
  src/main/java/com/weady/weady/domain/board/repository/BoardRepository.java
  src/main/java/com/weady/weady/domain/board/service/BoardService.java
  src/main/java/com/weady/weady/domain/weadychive/controller/board/WeadychiveBoardController.java
  src/main/java/com/weady/weady/domain/weadychive/dto/board/request/ScrapBoardRequestDto.java
  src/main/java/com/weady/weady/domain/weadychive/dto/board/response/ScrapBoardResponseDto.java
  src/main/java/com/weady/weady/domain/weadychive/dto/board/response/ScrappedBoardByUserResponseDto.java
  src/main/java/com/weady/weady/domain/weadychive/mapper/board/WeadychiveBoardMapper.java
  src/main/java/com/weady/weady/domain/weadychive/repository/board/WeadychiveBoardRepository.java
  src/main/java/com/weady/weady/domain/weadychive/service/board/WeadychiveBoardService.java
Labels: ✨ feat

#82 [FEAT] Board / 게시물 신고 기능 및 댓글 API 구현
  src/main/java/com/weady/weady/common/error/errorCode/BoardErrorCode.java
  src/main/java/com/weady/weady/domain/board/controller/BoardController.java
  src/main/java/com/weady/weady/domain/board/controller/CommentController.java
  src/main/java/com/weady/weady/domain/board/dto/request/CommentCreateRequestDto.java
  src/main/java/com/weady/weady/domain/board/dto/request/ReportRequestDto.java
  src/main/java/com/weady/weady/domain/board/dto/response/CommentResponseDto.java
  src/main/java/com/weady/weady/domain/board/dto/response/CommentWithChildResponseDto.java
  src/main/java/com/weady/weady/domain/board/entity/board/Report.java
  src/main/java/com/weady/weady/domain/board/entity/comment/BoardComment.java
  src/main/java/com/weady/weady/domain/board/mapper/BoardMapper.java
  src/main/java/com/weady/weady/domain/board/mapper/CommentMapper.java
  src/main/java/com/weady/weady/domain/board/repository/CommentRepository.java
  src/main/java/com/weady/weady/domain/board/repository/ReportRepository.java
  src/main/java/com/weady/weady/domain/board/service/BoardService.java
  src/main/java/com/weady/weady/domain/board/service/CommentService.java
Labels: ✨ feat

#85 [FEAT] Weather / 중기예보 조회 api 구현
  src/main/java/com/weady/weady/domain/weather/controller/WeatherController.java
  src/main/java/com/weady/weady/domain/weather/dto/response/GetWeatherMidDetailResponse.java
  src/main/java/com/weady/weady/domain/weather/entity/WeatherMidDetail.java
  src/main/java/com/weady/weady/domain/weather/mapper/WeatherMapper.java
  src/main/java/com/weady/weady/domain/weather/repository/WeatherMidDetailRepository.java
  src/main/java/com/weady/weady/domain/weather/repository/WeatherShortDetailRepository.java
  src/main/java/com/weady/weady/domain/weather/service/WeatherService.java
Labels: ✨ feat

#84 [FEAT] Weadychive , Curation / 웨디카이브 관련 API 및 큐레이션 관련 API 추가
  src/main/java/com/weady/weady/domain/curation/controller/CurationController.java
  src/main/java/com/weady/weady/domain/curation/dto/CurationCategoryResponse.java
  src/main/java/com/weady/weady/domain/curation/dto/CurationResponse.java
  src/main/java/com/weady/weady/domain/curation/dto/Response/CurationCategoryResponseDto.java
  src/main/java/com/weady/weady/domain/curation/entity/Curation.java
  src/main/java/com/weady/weady/domain/curation/entity/CurationCategory.java
  src/main/java/com/weady/weady/domain/curation/entity/CurationImg.java
  src/main/java/com/weady/weady/domain/curation/mapper/CurationCategoryMapper.java
  src/main/java/com/weady/weady/domain/curation/repository/curation/CurationRepository.java
  src/main/java/com/weady/weady/domain/curation/repository/curationCategory/CurationCategoryRepository.java
  src/main/java/com/weady/weady/domain/curation/service/CurationService.java
  src/main/java/com/weady/weady/domain/weadychive/controller/curation/WeadychiveController.java
  src/main/java/com/weady/weady/domain/weadychive/dto/curation/WeadychiveCurationRequest.java
  src/main/java/com/weady/weady/domain/weadychive/dto/curation/WeadychiveCurationResponse.java
  src/main/java/com/weady/weady/domain/weadychive/repository/curation/WeadychiveCurationRepository.java
  src/main/java/com/weady/weady/domain/weadychive/service/curation/WeadychiveCurationService.java
  src/main/java/com/weady/weady/domain/weather/repository/DailySummaryRepository.java
  src/main/java/com/weady/weady/global/common/error/errorCode/CurationErrorCode.java
  src/main/java/com/weady/weady/global/common/error/errorCode/DailySummaryErrorCode.java
Labels: ✨ feat

#91 [FEAT] 유저 즐겨찾기 지역 추가 api 수정 및 지역 날씨 미리보기 api 구현
  src/main/java/com/weady/weady/domain/user/controller/UserFavoriteLocationController.java
  src/main/java/com/weady/weady/domain/user/dto/request/AddUserFavoriteLocationRequest.java
  src/main/java/com/weady/weady/domain/weather/controller/WeatherController.java
  src/main/java/com/weady/weady/domain/weather/repository/WeatherMainRepository.java
  src/main/java/com/weady/weady/domain/weather/service/WeatherService.java
Labels: ✨ feat

#90 [FEAT] Board / 게시물 이미지 업로드 기능 추가
  src/main/java/com/weady/weady/common/external/s3/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/weady/weady/domain/board/controller/BoardController.java
  src/main/java/com/weady/weady/domain/board/dto/response/BoardHomeResponseDto.java
  src/main/java/com/weady/weady/domain/board/dto/response/BoardResponseDto.java
  src/main/java/com/weady/weady/domain/board/entity/board/Board.java
  src/main/java/com/weady/weady/domain/board/entity/board/BoardImg.java
  src/main/java/com/weady/weady/domain/board/mapper/BoardMapper.java
  src/main/java/com/weady/weady/domain/board/service/BoardService.java
Labels: ✨ feat
